after_script:
  - docker images

before_script:
  - cd "$VERSION"
  - IMAGE="machinecoin-core:${VERSION/\//-}"

env:
  - VERSION=0.14
  - VERSION=0.14/alpine

language: bash

script:
  - docker build -t "$IMAGE" .
  - docker run "$IMAGE" --version | grep "Machinecoin Core"

services: docker
